apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-miniproject-01
  labels:
    app: cloud-miniproject-01
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-miniproject-01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-miniproject-01
    spec:
      containers:
        - image: bkocis/cloud-miniproject-01
          imagePullPolicy: Always
          name: cloud-miniproject-01
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-miniproject-01
  labels:
    app: cloud-miniproject-01
spec:
  type: LoadBalancer
  selector:
    app: cloud-miniproject-01
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      protocol: TCP